Repository ooojin000/tasket, pull requests merged in 2025-03, with the labels that each got.

#2 [BE] feat: 디렉토리 구조 설정
  src/main/java/com/woojhye/tasket/alarm/controller/AlarmController.java
  src/main/java/com/woojhye/tasket/alarm/domain/Alarm.java
  src/main/java/com/woojhye/tasket/alarm/dto/AlarmDto.java
  src/main/java/com/woojhye/tasket/alarm/repository/AlarmRepository.java
  src/main/java/com/woojhye/tasket/alarm/service/AlarmService.java
  src/main/java/com/woojhye/tasket/task/controller/TaskController.java
  src/main/java/com/woojhye/tasket/task/domain/Task.java
  src/main/java/com/woojhye/tasket/task/dto/TaskDto.java
  src/main/java/com/woojhye/tasket/task/repository/TaskRepository.java
  src/main/java/com/woojhye/tasket/task/service/TaskService.java
  src/main/java/com/woojhye/tasket/user/controller/UserController.java
  src/main/java/com/woojhye/tasket/user/domain/User.java
  src/main/java/com/woojhye/tasket/user/dto/UserDto.java
  src/main/java/com/woojhye/tasket/user/repository/UserRepository.java
  src/main/java/com/woojhye/tasket/user/service/UserService.java
Labels: enhancement

#3 [FE] feat : 로그인, 회원가입 화면 구현
  src/main/resources/static/css/login.css
  src/main/resources/static/css/sign-up.css
  src/main/resources/static/img/tasket-logo-black.png
  src/main/resources/static/img/tasket-logo-white.png
  src/main/resources/static/img/tasket-logo.png
  src/main/resources/templates/contents/login.html
  src/main/resources/templates/contents/sign-up.html
Labels: frontend

#5 [FE] feat: 메인 화면 구현
  src/main/java/com/woojhye/tasket/TasketController.java
  src/main/resources/static/css/main.css
  src/main/resources/static/image/tasket-logo-black.png
  src/main/resources/static/image/tasket-logo-white.png
  src/main/resources/static/image/tasket-logo.png
  src/main/resources/static/js/main.js
  src/main/resources/templates/main.html
Labels: frontend

#6 [FE] feat : 화면 연결 및 파일 경로 수정
  src/main/java/com/woojhye/tasket/TasketController.java
  src/main/resources/static/img/tasket-logo-black.png
  src/main/resources/static/img/tasket-logo-white.png
  src/main/resources/static/img/tasket-logo.png
  src/main/resources/templates/contents/login.html
  src/main/resources/templates/contents/mypage.html
  src/main/resources/templates/contents/sign-up.html
Labels: frontend

#7 [FE] feat: 할일 프론트 개발
  src/main/resources/static/css/main.css
  src/main/resources/static/js/main.js
  src/main/resources/templates/main.html
Labels: frontend

#8 [FE] feat : 달력 화면 구현
  src/main/resources/static/css/main.css
  src/main/resources/static/js/main.js
  src/main/resources/templates/main.html
Labels: frontend

#9 [FE] feat : 노트 화면 구현
  src/main/resources/static/css/main.css
  src/main/resources/static/js/main.js
  src/main/resources/templates/contents/login.html
  src/main/resources/templates/main.html
Labels: frontend

#10 [FE] Feat: 프론트 화면 구현
  src/main/java/com/woojhye/tasket/TasketController.java
  src/main/resources/static/css/login.css
  src/main/resources/static/css/main.css
  src/main/resources/static/css/mypage.css
  src/main/resources/static/css/sign-up.css
  src/main/resources/static/image/tasket-logo-black.png
  src/main/resources/static/image/tasket-logo-white.png
  src/main/resources/static/image/tasket-logo.png
  src/main/resources/static/js/main.js
  src/main/resources/templates/contents/login.html
  src/main/resources/templates/contents/mypage.html
  src/main/resources/templates/contents/sign-up.html
  src/main/resources/templates/main.html
Labels: frontend

#11 [BE] feat: 유저, 베이스 엔티티 생성
  src/main/java/com/woojhye/tasket/base/BaseEntity.java
  src/main/java/com/woojhye/tasket/user/domain/User.java
Labels: backend

#13 [FE] feat :회원가입 이름 수정
  src/main/resources/templates/contents/sign-up.html
Labels: frontend
